# Generated by Django 4.2.9 on 2026-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('url_thumbnail', models.URLField()),
                ('canal_nombre', models.CharField(max_length=200)),
                ('vistas', models.BigIntegerField(default=0)),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
    ]
